### ISSUE TITLE
Ce Projet m'aveugle

### ISSUE THREAD

**Issue by rodvace** [sebastienOillic/planATroie#8]
![vtt](https://user-images.githubusercontent.com/41987349/43517552-6e170ada-9589-11e8-9b59-fd9749330cea.jpg)
Il faudrait ajouter un potard pour baisser la luminosité !
BIG Bug !!!

**Comment by maxime35370** [comment]
Le nouveau velo de Troie ?

**Comment by maxime35370** [comment]
C'est  Ok mais pourquoi ne pas éteindre la lumière directement

**Comment by sebastienOillic** [comment]
Genre un dark mode?

**Comment by maxime35370** [comment]
sa va finir en Plan à Troie dans le noir Attention

**Comment by rodvace** [comment]
Quel noir ?
Vincent McDoom ?
